<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_In-use</name>
   <tag></tag>
   <elementGuidId>c1ad83e2-3ccc-42e5-abbb-903468108eef</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[(text() = 'In-use' or . = 'In-use')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>div.mt-3.d-flex.justify-content-center.btn-off</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>49f631c6-f5a7-47cc-90f1-5fc5e7e9d4f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>mt-3 d-flex justify-content-center btn-off</value>
      <webElementGuid>f57bd50d-5498-45f2-adda-5a6eb9531630</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>In-use</value>
      <webElementGuid>9b273030-4ef2-4ac7-9ac7-b187e782ec21</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;id-chargers&quot;)/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col ant-col-12&quot;]/div[@class=&quot;indexstyle__DivCardChargerWrapper-pt__sc-1nvtvix-1 ddlrFp active&quot;]/div[@class=&quot;ant-row ant-row-center ant-row-middle py-3&quot;]/div[@class=&quot;ant-col ant-col-12 px-3 ant-col-xl-10&quot;]/div[@class=&quot;mt-3 d-flex justify-content-center btn-off&quot;]</value>
      <webElementGuid>5d57d696-c0d8-4c04-8d08-a3907bd19f61</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='id-chargers']/div/div/div/div/div/div</value>
      <webElementGuid>47991f8e-dba2-441f-bf30-a8d28793a049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='#12953fc1'])[1]/following::div[10]</value>
      <webElementGuid>21229b84-10ea-498f-9924-584b121294ea</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='RemoteStartTransaction'])[1]/preceding::div[5]</value>
      <webElementGuid>f4d8bd97-545b-4321-ad8a-667f004bc307</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Send'])[1]/preceding::div[7]</value>
      <webElementGuid>014ad7a4-de55-40ce-bb87-c2f766323981</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/div/div/div/div</value>
      <webElementGuid>2fecda32-2a47-48dc-9225-078d4f330749</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//div[(text() = 'In-use' or . = 'In-use')]</value>
      <webElementGuid>4f64cd7f-6ccb-4a73-b669-c1404dbf722f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
