<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Main Contact No_customers_contactPhone</name>
   <tag></tag>
   <elementGuidId>3dc97650-160a-4cc0-92f9-e4a624e99cca</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'customers_contactPhone' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#customers_contactPhone</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>a9633b93-fbfe-4428-bd66-1ce4c01914de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>37f3763b-f55a-4223-839a-8d71458f69a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customers_contactPhone</value>
      <webElementGuid>a828213f-1ff1-4328-bfb0-b937029a7691</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg indexstyle__InputWrapper-pt__sc-v8vmuq-0 ebLxPr undefined _input</value>
      <webElementGuid>23b6d26e-678c-470c-aeb7-199ab451daea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>53864d9b-5098-4388-9082-0a620db18265</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customers_contactPhone&quot;)</value>
      <webElementGuid>2e33a501-2ef6-4926-805f-8aa60b4a1b16</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'customers_contactPhone' and @type = 'text']</value>
      <webElementGuid>af76f344-7c63-4471-92b1-4e25f0b35b76</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customers_contactPhone']</value>
      <webElementGuid>63785b15-fe6f-449b-a113-4c54c9fa873d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customers']/div[5]/div[2]/div/div/div/div/input</value>
      <webElementGuid>f200767a-43f5-4570-94f0-2107780a9391</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[5]/div[2]/div/div/div/div/input</value>
      <webElementGuid>bbf746d8-08ce-4550-a3b1-6b30c4d3b290</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
