<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>li_Next</name>
   <tag></tag>
   <elementGuidId>190bf82e-a7f4-487d-b008-582a1284b957</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//li[@title = 'Next Page' and (text() = 'Next' or . = 'Next')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>li.ant-pagination-next</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>li</value>
      <webElementGuid>ab003629-fb6d-4a68-8bac-82d04ba1878c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>title</name>
      <type>Main</type>
      <value>Next Page</value>
      <webElementGuid>aacf3108-edfe-4b68-8ac4-d6471ae51b57</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tabindex</name>
      <type>Main</type>
      <value>0</value>
      <webElementGuid>faba317b-d4a8-4fe9-9159-0a02d81e9e77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-pagination-next</value>
      <webElementGuid>3db07bbc-e3d6-46bf-b71f-4a8f9c94f9c3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-disabled</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>18ffce50-039a-4d5a-b3dc-d6cfab996010</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Next</value>
      <webElementGuid>c01775ee-a1d5-4e01-84a3-0b8c9c772861</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;indexstyle__DivOrdersWrapper-pt__sc-1y1tn00-1 duqIpg customers__order&quot;]/div[@class=&quot;customers__order--wrapper&quot;]/div[@class=&quot;d-flex justify-content-end mt-4&quot;]/ul[@class=&quot;ant-pagination indexstyle__PaginationWrapper-pt__sc-1bdgnc5-0 cHVFvC&quot;]/li[@class=&quot;ant-pagination-next&quot;]</value>
      <webElementGuid>dde1b66c-aa71-4765-b47a-e430b389b23e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//li[@title = 'Next Page' and (text() = 'Next' or . = 'Next')]</value>
      <webElementGuid>674dc860-2422-481d-a2e5-28aab7f989bd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/main/div/div[3]/div[2]/ul/li[5]</value>
      <webElementGuid>94f0091b-eea9-486f-8640-de2ad521a51a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Previous'])[1]/following::li[4]</value>
      <webElementGuid>30c846b7-8ee9-4220-950c-4d59815aeeb8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Subscription Plan'])[9]/following::li[5]</value>
      <webElementGuid>1f0e56a5-ab2c-4ebe-8db4-643a3f2efab3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/ul/li[5]</value>
      <webElementGuid>0bda7721-fddb-480f-b9ca-51f3f5834bfa</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
