<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_Lite 19</name>
   <tag></tag>
   <elementGuidId>db2eca30-febd-4d70-af06-d7229117908c</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//p[(text() = ' Lite: 19' or . = ' Lite: 19')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>87b3a812-e039-4832-a94d-6b51347f0dac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>indexstyle__DivTextWrapper-pt__sc-yci0m8-0 iZqTEQ _p secondary-text d-flex align-items-center </value>
      <webElementGuid>d0ab90e2-beb5-43b8-a044-cfe474805dc9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value> Lite: 19</value>
      <webElementGuid>56d42033-6f28-46c5-bd1c-e07a5466f4d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;indexstyle__DivCustomerListWrapper-pt__sc-1y1tn00-0 kheJPy&quot;]/div[1]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;ant-row customer-wrapper&quot;]/div[@class=&quot;ant-col ant-col-24 ant-col-lg-12&quot;]/div[@class=&quot;indexstyle__DivCustomerCard-pt__sc-1y1tn00-2 kyxPzS box-container tx-detail-gray box-container__active&quot;]/div[@class=&quot;ant-row card-details&quot;]/div[@class=&quot;ant-col ant-col-12 ant-col-xl-8&quot;]/div[@class=&quot;mb-2 d-flex align-items-baseline&quot;]/p[@class=&quot;indexstyle__DivTextWrapper-pt__sc-yci0m8-0 iZqTEQ _p secondary-text d-flex align-items-center&quot;]</value>
      <webElementGuid>46ffdb29-6a99-47ee-9c5b-ad4aca5c396d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = ' Lite: 19' or . = ' Lite: 19')]</value>
      <webElementGuid>6aa13e05-de1e-4584-8f95-7b2b0df6e5f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/main/div/div/div/div/div/div/div/div[2]/div[2]/div/p</value>
      <webElementGuid>de8bb7e3-0a4b-4af9-9c3b-8356f8838b75</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Lyam 2 Test - Cartwright - Wuckert'])[1]/following::p[5]</value>
      <webElementGuid>ffe0afde-07cd-41ed-b85c-5e490d4c2caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ha Admin'])[1]/following::p[6]</value>
      <webElementGuid>895efd13-52ab-446e-8f11-5c46664698e7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Lite:']/parent::*</value>
      <webElementGuid>6b876a08-8b5c-4ca0-a36f-6913885e861d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/p</value>
      <webElementGuid>bd581198-473d-46f3-8230-aebc62a9f542</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
