<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EVC10 - 16 Amp_qrId</name>
   <tag></tag>
   <elementGuidId>e3274a89-9332-470c-86dd-739e4be1c5cb</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@name='qrId']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;qrId&quot;]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>aada2d33-1961-4c4a-9152-05a88e2d6ed1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>f8410246-fb92-4179-baf3-244ce120bb84</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>qrId</value>
      <webElementGuid>f6218f65-494d-427d-9f65-b3a0e9f30790</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input editable-cell</value>
      <webElementGuid>65098d09-d688-4bd2-925c-eb4985d61d11</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>3451246e-3a09-4e1f-8fc2-3dcf11783710</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[1]/div[@class=&quot;mx-auto&quot;]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;buttons undefined&quot;]/div[1]/div[@class=&quot;indexstyle__DivEditCommissionTableWrapper-pt__sc-1wmpx0r-1 lnRaNp box-container&quot;]/table[@class=&quot;w-100&quot;]/tbody[@class=&quot;table-body&quot;]/tr[@class=&quot;table-row&quot;]/td[@class=&quot;cell&quot;]/input[@class=&quot;ant-input editable-cell&quot;]</value>
      <webElementGuid>471e628e-9e64-4353-af12-f3ffb5b9ac92</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='qrId']</value>
      <webElementGuid>c441a3fb-73cd-425e-9b33-b9fcd05ff6f3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/main/div/div/div/div/div/div/div/table/tbody/tr/td[8]/input</value>
      <webElementGuid>17acc589-397e-4947-90a1-9e6dee60c292</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[8]/input</value>
      <webElementGuid>cd1e99d4-f0eb-4c23-8789-b02bf5280aac</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'qrId' and @type = 'text']</value>
      <webElementGuid>03c835e1-c248-4bd6-ae31-6d0a6e0cbda2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
