<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Enter QR ID_qrId</name>
   <tag></tag>
   <elementGuidId>34c4388a-330c-4951-8fe7-86bf15e6d0bf</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>#qrId</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@placeholder = 'e.g HLKSGSSA' and @id = 'qrId' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>dbc01ba2-12dc-410b-8ad1-f69fa027374d</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg my-4</value>
      <webElementGuid>27fd24b5-b82f-4372-9dfd-a2dc2fa33ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>e.g HLKSGSSA</value>
      <webElementGuid>774b00c7-736c-44af-a6c2-a62c5cb1255f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>qrId</value>
      <webElementGuid>b1f30515-df2b-40cd-836f-404ac6f8b8a8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-required</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>f8b832b1-746b-4ace-a06d-bd4fab26e939</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>fd9b6605-6b07-4151-a215-6abd858dd377</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;qrId&quot;)</value>
      <webElementGuid>81a53906-4b50-4045-94af-84e03c48245e</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@placeholder = 'e.g HLKSGSSA' and @id = 'qrId' and @type = 'text']</value>
      <webElementGuid>51d3140a-1004-4b79-b5d2-c615e9d11b0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='qrId']</value>
      <webElementGuid>3be6781c-a149-4731-b961-291b5aef1738</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>725c1784-a2bb-4981-b04d-32d679c1b725</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
