<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Unplug</name>
   <tag></tag>
   <elementGuidId>32296d07-ef17-4570-9d8d-798c61c3b102</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button' and (text() = 'Unplug' or . = 'Unplug')]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ant-btn.sc-pVTma.bZlNrp.danger</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>e9034660-2cdf-4189-9268-c4e0e0720ecd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>top</name>
      <type>Main</type>
      <value>24px</value>
      <webElementGuid>20bc91fc-cbf2-4a1e-b577-ccdcc1f9f2fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>bottom</name>
      <type>Main</type>
      <value>40px</value>
      <webElementGuid>749a5dd7-d82c-4bd9-90bb-f141bffa0b60</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>90eb6d22-0540-4401-b66b-8ed391e9efd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn sc-pVTma bZlNrp danger</value>
      <webElementGuid>f5b52760-af39-4d6b-b125-4d95dc30718f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Unplug</value>
      <webElementGuid>3cd76b0a-0906-46a4-9bd5-ea700ba99283</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;sc-bdvvaa fcglcb&quot;]/div[1]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;sc-gsDJrp jXLjZO&quot;]/div[1]/div[2]/button[@class=&quot;ant-btn sc-pVTma bZlNrp danger&quot;]</value>
      <webElementGuid>f210c21f-5528-4c7f-b42e-c09ef81df102</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[4]</value>
      <webElementGuid>7846261f-5070-4568-82fa-0cb949f4381e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/div/div[3]/div/div/div/div[2]/button</value>
      <webElementGuid>6568af43-8323-43ad-9202-b3f432f3544a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Disconnect'])[1]/following::button[1]</value>
      <webElementGuid>386cdb72-b915-4d8a-ac87-eb8275b6a933</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Connect another url ?'])[1]/following::button[2]</value>
      <webElementGuid>1509bb90-48cb-4fae-9577-c61c60ed5704</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Fault'])[1]/preceding::button[1]</value>
      <webElementGuid>9ad28ffe-d594-454a-acea-302669bb08a5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[3]/div/div/div/div[2]/button</value>
      <webElementGuid>275408bf-7f42-43d1-bf81-c6b00507138d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Unplug' or . = 'Unplug')]</value>
      <webElementGuid>29389f3f-7843-499a-9738-77209cbf2da4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
