<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>div_Dev_ant-switch-handle</name>
   <tag></tag>
   <elementGuidId>37c09e45-a0fa-4e5b-8831-09bb02f86900</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/div/div/button/div</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>button.ant-switch</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>div</value>
      <webElementGuid>396628fe-6fc8-4adb-87bb-e4f8f35a923c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-switch-handle</value>
      <webElementGuid>fddb7df2-d4a7-4780-8903-1b109f96ca97</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/div[1]/div[@class=&quot;sc-bdvvaa fcglcb&quot;]/button[@class=&quot;ant-switch env&quot;]/div[@class=&quot;ant-switch-handle&quot;]</value>
      <webElementGuid>c899a28d-13da-4c75-98cc-f3f3a6343104</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/div/div/button/div</value>
      <webElementGuid>8be5b2f0-2fb4-429c-8bc6-b51ea11ca122</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/div</value>
      <webElementGuid>635162ff-f24a-4395-ad6f-06ca333e6dd4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
