<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>button_Move to Test Orders</name>
   <tag></tag>
   <elementGuidId>23d4bb0e-0aef-424e-84eb-4c06b897dec3</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//button[@type = 'button' and (text() = 'Move to Test Orders' or . = 'Move to Test Orders')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>c733f07b-5e0e-45c7-927f-8ccd451b9af3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>button</value>
      <webElementGuid>7874ba5e-d680-4624-a6fb-5653711dce36</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-btn ant-btn-primary button__ButtonWrapper-pt__sc-1isy11p-0 hEeZRK _btn bold </value>
      <webElementGuid>c1c62076-b2ba-4e08-b173-3f29fc338c3f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Move to Test Orders</value>
      <webElementGuid>ac511422-fe8a-4d46-ab56-922003f896ac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>/html[1]/body[@class=&quot;ant-scrolling-effect&quot;]/div[5]/div[@class=&quot;ant-modal-root&quot;]/div[@class=&quot;ant-modal-wrap&quot;]/div[@class=&quot;ant-modal modal-order-detail inventoryOrderDetailModal&quot;]/div[@class=&quot;ant-modal-content&quot;]/div[@class=&quot;ant-modal-body&quot;]/div[@class=&quot;indexstyle__DivInventoryOrderDetailModal-pt__sc-19dkl0p-2 QOocj&quot;]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;pt-2 mt-5&quot;]/div[@class=&quot;bottom-actions mt-5 d-flex justify-content-end&quot;]/button[@class=&quot;ant-btn ant-btn-primary button__ButtonWrapper-pt__sc-1isy11p-0 hEeZRK _btn bold&quot;]</value>
      <webElementGuid>f351fb89-fd65-422e-9d99-035590eefabf</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//button[@type = 'button' and (text() = 'Move to Test Orders' or . = 'Move to Test Orders')]</value>
      <webElementGuid>b0413b6e-d059-490a-b430-7ef017a9a0bc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>(//button[@type='button'])[5]</value>
      <webElementGuid>dd420e02-f486-4965-ab8a-101fb5c91c27</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Edit Order'])[1]/following::button[1]</value>
      <webElementGuid>a84b04de-ec6a-4247-9350-5d867f443e58</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Delete'])[1]/following::button[2]</value>
      <webElementGuid>7b2950e2-49f5-4e26-9944-afb71ec20cf8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button[3]</value>
      <webElementGuid>2c241941-8e7b-4fdc-9e19-a5f1a8c5f1bf</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
