<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_PASSWORD_chargerId</name>
   <tag></tag>
   <elementGuidId>87653c8e-6c7b-453c-a5c1-14af5c00e50d</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;chargerId&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'chargerId' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>911f9291-b58e-439c-8ac7-28f57e495ac3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>457d18b7-ff9d-4a4d-96ac-ebeba1de349e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>chargerId</value>
      <webElementGuid>914bfc03-bcc2-4908-bdc5-1d9f2e88c658</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input editable-cell</value>
      <webElementGuid>9a78699a-8854-4630-a269-e09c3c581cec</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>168d318a-cf92-41a5-95af-c3c4e067d9e8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inventoryCommissioningMainTable&quot;)/tbody[@class=&quot;table-body&quot;]/tr[@class=&quot;table-row&quot;]/td[@class=&quot;cell&quot;]/input[@class=&quot;ant-input editable-cell&quot;]</value>
      <webElementGuid>17a8f01d-eae5-499d-b708-1c993d7f88b6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'chargerId' and @type = 'text']</value>
      <webElementGuid>3fe6a059-f234-46da-af36-ad68a42675de</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='chargerId']</value>
      <webElementGuid>93106c71-522f-4783-bc2a-6a600d66abef</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='inventoryCommissioningMainTable']/tbody/tr/td[4]/input</value>
      <webElementGuid>74f5806a-d121-427c-beee-16d30bd9e118</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[4]/input</value>
      <webElementGuid>29345439-63b2-4fbd-a10a-bac2de926bd2</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
