<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EVC10 - 48 Amp_qrId</name>
   <tag></tag>
   <elementGuidId>5c445524-400e-41ce-b0b2-d5bff124c61f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;qrId&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'qrId' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>1ecf23c2-bdd3-45b3-ad3c-ac965a89e5fd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>a39fe8ca-7305-4899-acc7-f8ba6893ae47</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>qrId</value>
      <webElementGuid>f1aee7af-fcd7-4042-a934-90fb4a013386</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input editable-cell</value>
      <webElementGuid>94ebf0a4-821e-4a41-bef8-da33ae9035c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2d141f42-6244-42ee-b00c-a6d3e095196b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inventoryCommissioningMainTable&quot;)/tbody[@class=&quot;table-body&quot;]/tr[@class=&quot;table-row&quot;]/td[@class=&quot;cell&quot;]/input[@class=&quot;ant-input editable-cell&quot;]</value>
      <webElementGuid>7fadaf03-a991-4ffa-8ff3-36eefb836043</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'qrId' and @type = 'text']</value>
      <webElementGuid>7f7c9bd5-fa29-4f64-a2f9-d948520cc095</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='qrId']</value>
      <webElementGuid>6839a27d-e274-4d96-a492-329af7a381be</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='inventoryCommissioningMainTable']/tbody/tr/td[6]/input</value>
      <webElementGuid>4c2f84ff-2683-4d3d-9ad1-8faba60b9caa</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[6]/input</value>
      <webElementGuid>bfce8576-1e8f-4b60-a59b-48ef9295bf30</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
