<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EVC10 - 48 Amp_serial</name>
   <tag></tag>
   <elementGuidId>a5384e33-d037-4ef4-b22b-b5f96617d230</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>input[name=&quot;serial&quot;]</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//input[@name = 'serial' and @type = 'text']</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>83627881-156f-4e69-953a-f8cffe45874b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>e06d292d-8a20-4bec-a6ba-4fa9b493e137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>name</name>
      <type>Main</type>
      <value>serial</value>
      <webElementGuid>a3dde064-cf63-4a8f-b5b7-22c2bffda7d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input editable-cell</value>
      <webElementGuid>44197326-0da5-4f37-99d5-03748ff312bf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>d2817e8d-aaeb-4df1-ae1d-3c2020d5daea</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;inventoryCommissioningMainTable&quot;)/tbody[@class=&quot;table-body&quot;]/tr[@class=&quot;table-row&quot;]/td[@class=&quot;cell&quot;]/input[@class=&quot;ant-input editable-cell&quot;]</value>
      <webElementGuid>a3c35c21-a21d-4447-a7ac-b0b49642fdb7</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@name = 'serial' and @type = 'text']</value>
      <webElementGuid>e4a92402-0eaf-4e81-821e-34fb356e9e67</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@name='serial']</value>
      <webElementGuid>ecb8da67-f4b5-47e9-8084-ecc4137c3e70</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//table[@id='inventoryCommissioningMainTable']/tbody/tr/td[5]/input</value>
      <webElementGuid>43226917-3087-41c5-8ad9-b7dd80ba4047</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//td[5]/input</value>
      <webElementGuid>0a83b7fd-be4a-4be2-9a48-ca8b69f4f312</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
