<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>p_H</name>
   <tag></tag>
   <elementGuidId>5b07bcb0-20ec-414a-b2e8-881612265e58</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//p[(text() = 'H' or . = 'H')]</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>b6006edc-e75f-4614-8bb1-fd1f9c03c7aa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>initial </value>
      <webElementGuid>0bc37597-d3d6-4b86-ab62-4e4b0ce57b41</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>H</value>
      <webElementGuid>46669202-acb7-4002-afb2-0e2f783d0061</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/header[@class=&quot;ant-layout-header header&quot;]/div[@class=&quot;h-100 data-center justify-content-between justify-content-md-end&quot;]/div[@class=&quot;indexstyle__DivTopBarRightWrapper-pt__sc-14j2cqw-1 gDroxQ topbar-right mr-3&quot;]/div[@class=&quot;ant-dropdown-trigger col user-menu-dropdown&quot;]/div[@class=&quot;rounded-circle text-center d-flex m-auto justify-content-center align-items-center&quot;]/p[@class=&quot;initial&quot;]</value>
      <webElementGuid>f0e044f1-ca05-46e7-8ebe-4ab155800930</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>p</value>
      <webElementGuid>d8bf0678-1860-4614-be81-3202ff6e1957</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>initial </value>
      <webElementGuid>d6453204-fb54-4fa2-9ac5-08e863039453</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>H</value>
      <webElementGuid>9419fa9c-4639-4d46-b1e1-3ef3c2545e48</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/header[@class=&quot;ant-layout-header header&quot;]/div[@class=&quot;h-100 data-center justify-content-between justify-content-md-end&quot;]/div[@class=&quot;indexstyle__DivTopBarRightWrapper-pt__sc-14j2cqw-1 gDroxQ topbar-right mr-3&quot;]/div[@class=&quot;ant-dropdown-trigger col user-menu-dropdown&quot;]/div[@class=&quot;rounded-circle text-center d-flex m-auto justify-content-center align-items-center&quot;]/p[@class=&quot;initial&quot;]</value>
      <webElementGuid>7027f129-d407-4bf4-b697-9f5b5b67e402</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//p[(text() = 'H' or . = 'H')]</value>
      <webElementGuid>9c99da7e-de8d-4527-aa9f-8b82876b61dc</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/header/div/div[2]/div[2]/div/p</value>
      <webElementGuid>71b59fb7-2f29-4b7d-9bce-3f55ead3e897</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ha OEM'])[1]/following::p[1]</value>
      <webElementGuid>7a3d7d2a-ee15-4d49-9aaa-4862ea15c432</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW ORDERS'])[1]/preceding::p[1]</value>
      <webElementGuid>f24d42bb-9b01-411c-b744-6609bdac8fd5</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order #127a5c45'])[1]/preceding::p[1]</value>
      <webElementGuid>12fed37e-6400-4ab4-ab19-e1328fe2df74</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='H']/parent::*</value>
      <webElementGuid>b5c0fc8a-b20f-48e8-bb06-fbb3dc6a8034</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//p</value>
      <webElementGuid>9cd155f9-d9be-421e-b62c-b642066dda77</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/header/div/div[2]/div[3]/div/p</value>
      <webElementGuid>c3ea5eb5-23e3-4d03-85f9-98234245d1c9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ha Admin'])[1]/following::p[1]</value>
      <webElementGuid>8a93cf06-caa9-4dd5-995b-2fc10e721e30</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QUEUE (13)'])[1]/preceding::p[2]</value>
      <webElementGuid>1ef7538b-5103-407b-aad9-4d028fd4b02d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order #12196cd5'])[1]/preceding::p[2]</value>
      <webElementGuid>aed6f99f-cd8e-456e-8235-efaff26ee26e</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
