<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Ha OEM_anticon anticon-plus-circle</name>
   <tag></tag>
   <elementGuidId>9167937c-7027-4b48-ba66-065571791c9f</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.anticon.anticon-plus-circle</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/section/main/div/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>e38c48ce-062a-43a4-9e92-7f1a6eda3eb9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>role</name>
      <type>Main</type>
      <value>img</value>
      <webElementGuid>e4e15dfc-00ff-4903-a6e5-e09fb6d11d9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-label</name>
      <type>Main</type>
      <value>plus-circle</value>
      <webElementGuid>e920ab3d-ea7b-40f1-8b2d-a6f6654d7c75</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>size</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>5f897b8c-95a3-45e2-bd08-903da23ae3b3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>anticon anticon-plus-circle</value>
      <webElementGuid>bd3d77a8-b642-482c-ba07-c1d42e5568a1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;indexstyle__DivHomeWrapper-pt__sc-fwxsmq-0 kcRNeo&quot;]/div[@class=&quot;d-flex align-items-center action-header&quot;]/button[@class=&quot;ant-btn ant-btn-icon-only button__ButtonWrapper-pt__sc-1isy11p-0 hEeZRK _btn bold p-0 btn-create-order&quot;]/span[@class=&quot;anticon anticon-plus-circle&quot;]</value>
      <webElementGuid>d559e1c8-26f1-4778-96a6-470523a4d9dd</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/main/div/div/button/span</value>
      <webElementGuid>8e23043e-aa61-4a29-9fb0-0c6392fa79e1</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ha OEM'])[1]/following::span[1]</value>
      <webElementGuid>5b093ed4-0205-4477-9acd-c2be2a8076c2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW ORDERS'])[1]/preceding::span[1]</value>
      <webElementGuid>c03d4bf1-fb18-4fa5-a1f8-94c35a8f95a9</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order #127bb8e8'])[1]/preceding::span[2]</value>
      <webElementGuid>c9ed5b16-e7b4-4c94-b6cb-8c1be9b9406d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//button/span</value>
      <webElementGuid>c001b735-2a60-42a0-8ff3-7b9b2acb82e1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
