<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg</name>
   <tag></tag>
   <elementGuidId>580ddaea-d5f1-441d-9d14-ba7bf6110b74</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>span.anticon.anticon-plus-circle > svg</value>
      </entry>
      <entry>
         <key>XPATH</key>
         <value>/html/body/div[1]/section/section/main/div/button/span</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>8bedfc5a-6f1e-432a-ae50-4ec3c285ec54</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>64 64 896 896</value>
      <webElementGuid>8e70a97c-f136-4e02-993c-da447a53b3de</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>f5837960-3af4-40bf-bcb7-649ce6284b77</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>plus-circle</value>
      <webElementGuid>8c44cbd2-6d5c-42a3-a5a7-164bc71a90a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>622a05d6-bf1c-46c1-b391-7c3bf59574cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>b642a2df-285b-4dc7-b2dd-f5a291de0181</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>2d680fae-da8d-45a2-8df9-d4dfa5b8149c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>a727f1b0-bee5-45cf-87f9-d01ef9f4eed8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;indexstyle__DivOrderBoardInternal-pt__sc-1118qaq-0 ePiSip&quot;]/button[@class=&quot;ant-btn ant-btn-icon-only button__ButtonWrapper-pt__sc-1isy11p-0 dOvqbV _btn bold add-job ant-tooltip-open&quot;]/span[@class=&quot;anticon anticon-plus-circle&quot;]/svg[1]</value>
      <webElementGuid>3b81f986-61b5-4a36-a106-dccbba5d51c6</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ly Duong (Admin)'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>c24bfdee-2c2f-4409-9ad4-20723021d966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW JOBS'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>8de8dc15-aa1a-4f4a-9a5a-c6284b2a2a0e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='INSTALLED JOBS'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>6d0517eb-7f97-406d-8908-d0211b90f4f4</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
