<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>b_1200d28b</name>
   <tag></tag>
   <elementGuidId>7d06263b-eef8-4986-a1c6-abea25bf19db</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//div[@id='root']/section/section/main/div/div/div[2]/p[2]/b</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#createdOrderId</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>60856285-0f90-459e-9708-fb5e6ab420e9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tx-primary</value>
      <webElementGuid>40f699f6-0a42-4d3b-a0e8-15de0db427ad</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>#1200d28b</value>
      <webElementGuid>0c430043-4b8b-4bdf-99aa-e264a9172d81</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;indexstyle__DivDeploymentWrapper-pt__sc-1nlz5zm-1 cljbtb&quot;]/div[@class=&quot;mx-auto&quot;]/div[@class=&quot;box-container mx-auto text-center py-5 mt-4&quot;]/p[@class=&quot;mb-3&quot;]/b[@class=&quot;tx-primary&quot;]</value>
      <webElementGuid>a0244e9a-6f5c-4506-b1db-09ee98e25708</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>b</value>
      <webElementGuid>5fd6a03b-85f4-415c-96c7-c14cada5440b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>tx-primary</value>
      <webElementGuid>0028f200-27e2-491a-be84-e51521e4795c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>#1200d28b</value>
      <webElementGuid>e09ff56b-2838-4da9-8a16-3fe72d6f0bd2</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;indexstyle__DivDeploymentWrapper-pt__sc-1nlz5zm-1 cljbtb&quot;]/div[@class=&quot;mx-auto&quot;]/div[@class=&quot;box-container mx-auto text-center py-5 mt-4&quot;]/p[@class=&quot;mb-3&quot;]/b[@class=&quot;tx-primary&quot;]</value>
      <webElementGuid>3f1991fd-90f9-4757-950c-6632dccfe5cc</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/main/div/div/div[2]/p[2]/b</value>
      <webElementGuid>9beba634-c930-4aa0-b192-49dd390f5303</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Pre-Shipment Form'])[1]/following::b[1]</value>
      <webElementGuid>5ef04e60-a0c7-4e33-8cbc-321f8744bcdd</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='NEW DEPLOYMENT'])[1]/following::b[1]</value>
      <webElementGuid>95f7c1de-c045-4b8a-b199-3bb496fdee98</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back to Dashboard'])[1]/preceding::b[1]</value>
      <webElementGuid>2f0b767a-66d4-4981-aff8-d1f39e48e100</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='#']/parent::*</value>
      <webElementGuid>b9fdd57c-1078-45b3-a11f-88e012b21c22</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//b</value>
      <webElementGuid>0ad78384-f164-46d7-8e15-94b1e4a493c6</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//b[(text() = '#1200d28b' or . = '#1200d28b')]</value>
      <webElementGuid>fab648c2-2bf8-4d5a-b20a-71939d935e6b</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
