<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>Create Order Button</name>
   <tag></tag>
   <elementGuidId>ef86dbf7-1781-46fe-a7dc-4eb3be3d51fa</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='Ha Admin'])[1]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>.btn-create-order</value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>4af16042-6955-4d87-bb48-7895a7fa5c34</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>64 64 896 896</value>
      <webElementGuid>51245156-a574-4e4c-aa6b-459855d50774</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>focusable</name>
      <type>Main</type>
      <value>false</value>
      <webElementGuid>4ce87194-a02f-423f-9664-275cbede4825</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>data-icon</name>
      <type>Main</type>
      <value>plus-circle</value>
      <webElementGuid>65d60073-d034-404a-8f85-6c04e933fa64</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>b298fef0-9faa-45ba-9ff1-ad5291718f29</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>1em</value>
      <webElementGuid>0248567c-7b39-44a6-8cb4-65a8ad7d4e7e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>b490f2b6-09f6-4bbd-a226-c166f556ee09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>aria-hidden</name>
      <type>Main</type>
      <value>true</value>
      <webElementGuid>3ee97952-9a49-4c77-90eb-6b518f55f54c</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;indexstyle__DivHomeWrapper-pt__sc-fwxsmq-0 kcRNeo&quot;]/div[@class=&quot;d-flex align-items-center action-header&quot;]/button[@class=&quot;ant-btn ant-btn-icon-only button__ButtonWrapper-pt__sc-1isy11p-0 hEeZRK _btn bold p-0 btn-create-order&quot;]/span[@class=&quot;anticon anticon-plus-circle&quot;]/svg[1]</value>
      <webElementGuid>7281fc0e-241c-42c4-b7b8-483a8e8b4949</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Ha Admin'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>b4c87249-9b9b-4c60-a998-65272ef36b38</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='QUEUE (10)'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>d51cf319-9ccb-49b6-b06a-855f9abc9a5d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Order #12b19aed'])[1]/preceding::*[name()='svg'][2]</value>
      <webElementGuid>9cf48a96-def6-4e74-b8a8-2d31fe901b19</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
