<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company Name_customers_companyName</name>
   <tag></tag>
   <elementGuidId>200d2634-3e34-4dfe-8327-cb77ffb1ae33</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'customers_companyName' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#customers_companyName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>64ea9f27-93e2-4c2a-a242-f32392257215</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>d61941d8-ee84-49ce-8f17-01479c2877d0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customers_companyName</value>
      <webElementGuid>76699a6b-0923-4a7a-b0ad-c42799f0bb83</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg indexstyle__InputWrapper-pt__sc-v8vmuq-0 jueGXX undefined _input</value>
      <webElementGuid>92ad4128-54d2-4b95-8461-28f87adc79c1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>a31d35cc-672c-4af1-ad56-1b13c41a48fa</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customers_companyName&quot;)</value>
      <webElementGuid>8c791bad-c025-48b4-b187-f69a07e5a376</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'customers_companyName' and @type = 'text']</value>
      <webElementGuid>2f2a95db-fc05-48ca-b502-28a750e021d2</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customers_companyName']</value>
      <webElementGuid>410d01da-7249-4eab-aa90-2d4db7549c4b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>(//form[@id='customers']/div[2]/div[2]/div/div/div/div/input)[2]</value>
      <webElementGuid>72132d94-b9cd-4da8-a606-6025f85ce1b3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div/div[2]/div/div/form/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>6b01c4a4-fa3c-41d7-adea-175df889e7f8</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
