<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>span_Submit</name>
   <tag></tag>
   <elementGuidId>b6ecc6e8-efe3-4015-a1e6-7e38692c0c7e</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//span[(text() = 'Submit' or . = 'Submit')]</value>
      </entry>
      <entry>
         <key>CSS</key>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>fc082e55-edce-48ca-85ed-060bd61ebb09</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>16c65067-fbbf-46a9-96c9-f3f81af520e0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;indexstyle__DivDeploymentWrapper-pt__sc-1nlz5zm-1 cljbtb&quot;]/div[@class=&quot;mx-auto&quot;]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;step-actions&quot;]/div[@class=&quot;next-actions&quot;]/button[@class=&quot;ant-btn ant-btn-primary ant-btn-lg button__ButtonWrapper-pt__sc-1isy11p-0 hEeZRK _btn bold&quot;]/span[1]</value>
      <webElementGuid>ac727ae8-f1b8-4657-8b24-014c8b38ba9a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>span</value>
      <webElementGuid>f6b74529-3c4b-408c-8c1e-8d1980f992e6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>text</name>
      <type>Main</type>
      <value>Submit</value>
      <webElementGuid>becee2db-5288-4a45-8da2-33c96ffa656b</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;indexstyle__DivDeploymentWrapper-pt__sc-1nlz5zm-1 cljbtb&quot;]/div[@class=&quot;mx-auto&quot;]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;step-actions&quot;]/div[@class=&quot;next-actions&quot;]/button[@class=&quot;ant-btn ant-btn-primary ant-btn-lg button__ButtonWrapper-pt__sc-1isy11p-0 hEeZRK _btn bold&quot;]/span[1]</value>
      <webElementGuid>89eb55d6-fc4b-4e33-a016-03e6b5010875</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/main/div/div/div[2]/div/div[2]/div[2]/button/span</value>
      <webElementGuid>2160da4f-0281-439f-b0e7-0d38ec36af19</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Back'])[1]/following::span[1]</value>
      <webElementGuid>84694a30-bcf5-4efd-9116-5b6bf4af095c</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Sim'])[1]/following::span[2]</value>
      <webElementGuid>6bb79ac4-2b35-483a-bda4-f6f5cc356a95</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft Saved'])[1]/preceding::span[2]</value>
      <webElementGuid>19a43dd1-fe72-4cca-88d0-ffc3ee18330e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Draft order has been auto-saved successfully!'])[1]/preceding::span[2]</value>
      <webElementGuid>24edac8a-e2e9-4f1a-ab79-39e3c57d5049</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>//*/text()[normalize-space(.)='Submit']/parent::*</value>
      <webElementGuid>712f2d02-27ec-4aca-aa24-856245f26ea8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/button/span</value>
      <webElementGuid>764217ae-d322-41d3-bed3-9c2217def803</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//span[(text() = 'Submit' or . = 'Submit')]</value>
      <webElementGuid>2ac9fd5d-033b-49b7-8925-7aa8c3c257f1</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
