<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>welcome-user</name>
   <tag></tag>
   <elementGuidId>b1e0b178-1ac1-477c-9d48-dfb481612ac1</elementGuidId>
   <selectorCollection>
      <entry>
         <key>CSS</key>
         <value>.welcome-user</value>
      </entry>
      <entry>
         <key>BASIC</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>CSS</selectorMethod>
   <useRalativeImagePath>false</useRalativeImagePath>
</WebElementEntity>
