<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_EVC11 - 48 Amp_chargerSpecs_1_numberOfUnits</name>
   <tag></tag>
   <elementGuidId>05a7eb46-69fa-4378-8002-a21be2c226a9</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'chargerSpecs_1_numberOfUnits' and @type = 'number']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#chargerSpecs_1_numberOfUnits</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2c5f61c6-6b6a-436a-a83c-10e02377950f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>948ae599-b581-436e-9973-cbda16c317d1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>chargerSpecs_1_numberOfUnits</value>
      <webElementGuid>941b1f09-9598-4691-b33d-59fa4710edc7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg</value>
      <webElementGuid>f023a529-8044-47b4-9e23-f10176542e5e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>number</value>
      <webElementGuid>5660101e-b175-4d17-b706-800e0e272158</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>1</value>
      <webElementGuid>83bec1f9-f78f-4947-9d82-689774dfd55f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;chargerSpecs_1_numberOfUnits&quot;)</value>
      <webElementGuid>e8464d98-0ebc-470d-aa51-d80ff49c7d2b</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'chargerSpecs_1_numberOfUnits' and @type = 'number']</value>
      <webElementGuid>ef24b607-d388-4ffc-9f25-8157b6a756d8</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='chargerSpecs_1_numberOfUnits']</value>
      <webElementGuid>000f6dfe-5148-42f8-b302-1549041e218e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/main/div/div/div/div/form/div/div/div[8]/div/div[2]/div/div/div/div[2]/div/div/div/div/span/span/input</value>
      <webElementGuid>3b22b0c4-01c8-493b-ab9a-a5aa42397b78</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[8]/div/div[2]/div/div/div/div[2]/div/div/div/div/span/span/input</value>
      <webElementGuid>282e1a88-9cb6-46e4-aab1-367d7aa8c935</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
