<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Address_locations_address</name>
   <tag></tag>
   <elementGuidId>562f9a3b-2e6a-45b4-b5ab-2880534ba739</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'locations_address']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#locations_address</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>f82314b8-c9de-44e2-8aa6-0a886a9238fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>locations_address</value>
      <webElementGuid>32d7c49d-8432-4f20-a94c-8253ec9ff7c0</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>w-100 input-search-place pac-target-input</value>
      <webElementGuid>a0aba947-69f9-4c36-b576-671b147371f4</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>836851b7-e6b7-4904-9a6d-518738aec3cd</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;locations_address&quot;)</value>
      <webElementGuid>e3102788-5e7f-4218-955b-2b1c404c04e1</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'locations_address']</value>
      <webElementGuid>a57e597c-36e1-417b-b548-049d4e26e0b7</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='locations_address']</value>
      <webElementGuid>c8ad979c-2fcc-4d46-9d2e-77b1ceb1aa0d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='locations']/div[4]/div[2]/div/div/div/div/input</value>
      <webElementGuid>42cff1bb-f3b3-46a0-9ab9-d44ae6677e9e</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[4]/div[2]/div/div/div/div/input</value>
      <webElementGuid>4e86bc9f-ee24-415f-a594-c825247a407d</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
