<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Root Account Email_customers_email</name>
   <tag></tag>
   <elementGuidId>4e03bf73-a053-423a-9fd1-aede9c145a0a</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'customers_email' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#customers_email</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>181ee487-e6ab-45b9-ba10-93fe42b40af9</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>a3a7903f-937a-46a5-8734-5c99ee8177f8</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customers_email</value>
      <webElementGuid>ae3af22a-a465-40ef-af8a-238d8357d057</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg indexstyle__InputWrapper-pt__sc-v8vmuq-0 jueGXX undefined _input</value>
      <webElementGuid>53b36a51-2640-484c-aae6-c387ac02330a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>53aff958-dd04-4620-86fe-8f17061b41cb</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>value</name>
      <type>Main</type>
      <value>l</value>
      <webElementGuid>f61898ce-f165-41dc-bc5d-4bf6fd993b33</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customers_email&quot;)</value>
      <webElementGuid>29d23cf6-d9d3-4e9a-9944-0f59fae84805</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'customers_email' and @type = 'text']</value>
      <webElementGuid>862695fb-941f-4f11-af09-e319b7a66516</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customers_email']</value>
      <webElementGuid>349c058a-f037-48da-b802-77951c0db9f4</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customers']/div[6]/div[2]/div/div/div/div/input</value>
      <webElementGuid>a47ed360-0319-4bb1-a3e6-9563f66e6f21</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[6]/div[2]/div/div/div/div/input</value>
      <webElementGuid>dab2752b-7b43-4857-b72a-d124e6e3be1f</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
