<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Job Creator Form_installers_0_name</name>
   <tag></tag>
   <elementGuidId>1010d876-44ba-41c9-a38f-b8bf6d4cf4ce</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'installers_0_name' and @placeholder = 'Name' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#installers_0_name</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>2898d4a0-91f2-4af4-82db-86b52ab4cf49</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>off</value>
      <webElementGuid>a5c47d11-a374-4399-bea0-68e8ae080f9e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>installers_0_name</value>
      <webElementGuid>08be710a-ed97-471d-84f2-222c9a34892f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg indexstyle__InputWrapper-pt__sc-v8vmuq-0 jueGXX undefined _input</value>
      <webElementGuid>3d6d632f-34d8-4ff8-8e50-f600023eecf6</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>placeholder</name>
      <type>Main</type>
      <value>Name</value>
      <webElementGuid>7f57e398-2f65-4278-819c-d26e0541a8f3</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>2e7e0364-f0c4-470e-81f9-201d083f4fe1</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;installers_0_name&quot;)</value>
      <webElementGuid>4c87db69-a4a9-47c7-9b18-b282c6d8947d</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'installers_0_name' and @placeholder = 'Name' and @type = 'text']</value>
      <webElementGuid>7b978140-5870-42cb-b171-33cb3e65f966</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='installers_0_name']</value>
      <webElementGuid>57199406-dc51-4491-ada3-bc35f6952824</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//div[@id='root']/section/section/main/div/div/div/div/form/div/div/div/div/div[2]/div/div/div/div/div/div/div/div/input</value>
      <webElementGuid>ddb95ecf-48c9-468a-bcc8-41f0ed2a9c0b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//input</value>
      <webElementGuid>3f4e38ea-57da-4597-8146-c9a2da6de123</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
