<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>input_Company Name_customers_companyName</name>
   <tag></tag>
   <elementGuidId>5976917c-b378-456a-989b-1e57d8d916ee</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>//input[@id = 'customers_companyName' and @type = 'text']</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value>#customers_companyName</value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>input</value>
      <webElementGuid>52ee0e1c-f409-4279-878d-7cdf320aea4f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>autocomplete</name>
      <type>Main</type>
      <value>nope</value>
      <webElementGuid>bc801d09-7640-44bf-88aa-1aa995671251</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>id</name>
      <type>Main</type>
      <value>customers_companyName</value>
      <webElementGuid>4235d67c-4200-4ac7-aed1-17b6c79f64a5</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>ant-input ant-input-lg indexstyle__InputWrapper-pt__sc-v8vmuq-0 jueGXX undefined _input</value>
      <webElementGuid>9d03e261-8414-4792-b315-7d111b29eb1e</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>type</name>
      <type>Main</type>
      <value>text</value>
      <webElementGuid>0f59f40b-a369-418d-a8b0-f0cd96efcde7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;customers_companyName&quot;)</value>
      <webElementGuid>5c8819bc-ecf0-4946-9fe7-aa139758ab91</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:customAttributes</name>
      <type>Main</type>
      <value>//input[@id = 'customers_companyName' and @type = 'text']</value>
      <webElementGuid>c4b51c37-253e-4726-976b-f721b721cb6d</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:attributes</name>
      <type>Main</type>
      <value>//input[@id='customers_companyName']</value>
      <webElementGuid>da8f8981-4573-40c6-8a3d-53c3f0cf769a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:idRelative</name>
      <type>Main</type>
      <value>//form[@id='customers']/div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>103e9927-c34f-47bd-9974-682b48cd8c1b</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:position</name>
      <type>Main</type>
      <value>//div[2]/div[2]/div/div/div/div/input</value>
      <webElementGuid>ea2affd5-d556-4321-815c-3050711f7bea</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
