<?xml version="1.0" encoding="UTF-8"?>
<WebElementEntity>
   <description></description>
   <name>svg_units_feather feather-plus</name>
   <tag></tag>
   <elementGuidId>a66021dc-fdd6-4a0c-906c-483c51865e55</elementGuidId>
   <selectorCollection>
      <entry>
         <key>XPATH</key>
         <value>(.//*[normalize-space(text()) and normalize-space(.)='units'])[1]/following::*[name()='svg'][1]</value>
      </entry>
      <entry>
         <key>CSS</key>
         <value></value>
      </entry>
   </selectorCollection>
   <selectorMethod>XPATH</selectorMethod>
   <useRalativeImagePath>true</useRalativeImagePath>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>tag</name>
      <type>Main</type>
      <value>svg</value>
      <webElementGuid>954f872e-b03b-4095-93bd-0c14abb387cf</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>width</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>23a77455-d8e9-41e9-8b2d-f4db229954fc</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>height</name>
      <type>Main</type>
      <value>24</value>
      <webElementGuid>3b166a30-f814-4bd6-81bf-35af7c268fac</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>viewBox</name>
      <type>Main</type>
      <value>0 0 24 24</value>
      <webElementGuid>b88d8c92-625d-4478-a71b-7bed67e19087</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>fill</name>
      <type>Main</type>
      <value>none</value>
      <webElementGuid>7546c43b-4f30-4924-b81b-e77d99a75137</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke</name>
      <type>Main</type>
      <value>currentColor</value>
      <webElementGuid>3ef2ad28-7190-4da8-9f82-af13b55c969f</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-width</name>
      <type>Main</type>
      <value>2</value>
      <webElementGuid>d6222515-24b0-4c1f-8eec-fee8021ba885</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linecap</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>e9666c74-2983-4e04-8d83-acc090edac26</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>stroke-linejoin</name>
      <type>Main</type>
      <value>round</value>
      <webElementGuid>83bdfc8b-2948-4277-afe7-a578cfd2cbe7</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>class</name>
      <type>Main</type>
      <value>feather feather-plus </value>
      <webElementGuid>92f321c0-1665-4f5b-a5ac-45f1b968687a</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>color</name>
      <type>Main</type>
      <value>#00DC9A</value>
      <webElementGuid>2c1a3474-38db-4d90-8846-e659237c1462</webElementGuid>
   </webElementProperties>
   <webElementProperties>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath</name>
      <type>Main</type>
      <value>id(&quot;root&quot;)/section[@class=&quot;ant-layout ant-layout-has-sider&quot;]/section[@class=&quot;ant-layout&quot;]/main[@class=&quot;ant-layout-content&quot;]/div[@class=&quot;ant-spin-nested-loading&quot;]/div[@class=&quot;ant-spin-container&quot;]/div[@class=&quot;indexstyle__DivDeploymentWrapper-pt__sc-1nlz5zm-1 flfHaT&quot;]/div[@class=&quot;indexstyle__DivLocationInfoWrapper-pt__sc-1nlz5zm-2 indexstyle__DevCreateInventoryOrderInfoWrapper-pt__sc-1nlz5zm-3 gFpcHV jSmTBT m-auto&quot;]/form[@class=&quot;ant-form ant-form-horizontal ant-form-hide-required-mark form-locations box-container&quot;]/div[@class=&quot;ant-row justify-content-center&quot;]/div[@class=&quot;ant-col ant-col-20&quot;]/div[@class=&quot;form-item-wrapper position-relative&quot;]/div[@class=&quot;ant-row ant-form-item mb-0&quot;]/div[@class=&quot;ant-col ant-col-24 ant-form-item-control&quot;]/div[@class=&quot;ant-form-item-control-input&quot;]/div[@class=&quot;ant-form-item-control-input-content&quot;]/div[@class=&quot;ant-row&quot;]/div[@class=&quot;ant-col ant-col-4&quot;]/div[@class=&quot;d-flex align-items-center&quot;]/span[@class=&quot;indexstyle__DivTextWrapper-pt__sc-yci0m8-0 cMprTC _p secondary-text ellipsis ant-tooltip-open&quot;]/button[@class=&quot;ant-btn ant-btn-link button__ButtonWrapper-pt__sc-1isy11p-0 dOvqbV _btn bold px-2 ml-2&quot;]/svg[@class=&quot;feather feather-plus&quot;]</value>
      <webElementGuid>221a2856-894c-4253-8e36-2246e4c4c412</webElementGuid>
   </webElementProperties>
   <webElementXpaths>
      <isSelected>true</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='units'])[1]/following::*[name()='svg'][1]</value>
      <webElementGuid>c6fd4863-1f93-4674-a4ef-7de18f4e4c8a</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='EVC10 - 48 Amp'])[1]/following::*[name()='svg'][2]</value>
      <webElementGuid>35b3a1ba-10bd-458b-a424-9a2b2267f038</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Cancel'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>7227835b-90b4-4ed0-9d4f-661e44f4f4d3</webElementGuid>
   </webElementXpaths>
   <webElementXpaths>
      <isSelected>false</isSelected>
      <matchCondition>equals</matchCondition>
      <name>xpath:neighbor</name>
      <type>Main</type>
      <value>(.//*[normalize-space(text()) and normalize-space(.)='Create Job'])[1]/preceding::*[name()='svg'][1]</value>
      <webElementGuid>76ba53b6-b43f-4b57-b876-2476432f2c3a</webElementGuid>
   </webElementXpaths>
</WebElementEntity>
